"""methods application_steps

Revision ID: b140134d9bc2
Revises: 0c7ee9887f46
Create Date: 2026-09-04 12:34:16.291340

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# Идентификатор ревизии; используется Alembic.
revision: str = 'b140134d9bc2'
down_revision: str | None = '0c7ee9887f46'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default нужен существующим строкам: SQLite не умеет добавить
    # NOT NULL колонку в непустую таблицу без значения по умолчанию.
    with op.batch_alter_table('methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_steps', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('methods', schema=None) as batch_op:
        batch_op.drop_column('application_steps')

    # ### end Alembic commands ###
