"""Первичная схема базы инженерных знаний.

Создаёт все таблицы, которыми управляет приложение, вместе с ограничениями
целостности: перечень допустимых статусов, диапазоны числовых оценок и
уникальность пар в конфликтах. Ограничения продублированы в схеме, чтобы ни
один запрос в обход приложения не мог записать значение, нарушающее инварианты
каталога.

Revision ID: cdf89f70b108
Revises:
Create Date: 2026-09-03 17:16:39.387357

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# Идентификатор ревизии; используется Alembic.
revision: str = 'cdf89f70b108'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a_code', sa.String(length=64), nullable=False),
    sa.Column('b_code', sa.String(length=64), nullable=False),
    sa.Column('conflict_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('draft', 'reviewed', 'published')", name='ck_status_values'),
    sa.CheckConstraint('a_code <> b_code', name='ck_conflicts_distinct'),
    sa.CheckConstraint('severity between 1 and 3', name='ck_conflicts_severity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a_code', 'b_code', 'conflict_type', name='uq_conflict_pair')
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicts_a_code'), ['a_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicts_b_code'), ['b_code'], unique=False)

    op.create_table('engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('vendor', sa.String(length=120), nullable=False),
    sa.Column('versions', sa.JSON(), nullable=False),
    sa.Column('supported_formats', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('docs_url', sa.String(length=600), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('draft', 'reviewed', 'published')", name='ck_status_values'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_engines_code')
    )
    with op.batch_alter_table('engines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engines_code'), ['code'], unique=False)

    op.create_table('game_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('developer', sa.String(length=200), nullable=False),
    sa.Column('engine', sa.String(length=80), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('world_type', sa.String(length=20), nullable=False),
    sa.Column('scale', sa.String(length=20), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('target_resolution', sa.String(length=20), nullable=False),
    sa.Column('target_fps', sa.Integer(), nullable=False),
    sa.Column('object_count_level', sa.String(length=10), nullable=False),
    sa.Column('npc_count_level', sa.String(length=10), nullable=False),
    sa.Column('multiplayer', sa.Boolean(), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('optimizations_used', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('performance_outcome', sa.Text(), nullable=False),
    sa.Column('source_title', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=False),
    sa.Column('source_date', sa.String(length=20), nullable=False),
    sa.Column('verified_by', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('draft', 'reviewed', 'published')", name='ck_status_values'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', name='uq_game_examples_title')
    )
    with op.batch_alter_table('game_examples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_examples_status'), ['status'], unique=False)

    op.create_table('game_functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('formats', sa.JSON(), nullable=False),
    sa.Column('typical_world_types', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_title', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=False),
    sa.Column('source_date', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('draft', 'reviewed', 'published')", name='ck_status_values'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_game_functions_code')
    )
    with op.batch_alter_table('game_functions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_functions_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_functions_status'), ['status'], unique=False)

    op.create_table('hardware_cpu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('generation', sa.String(length=80), nullable=False),
    sa.Column('architecture', sa.String(length=80), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=False),
    sa.Column('cores', sa.Integer(), nullable=False),
    sa.Column('threads', sa.Integer(), nullable=False),
    sa.Column('base_clock_ghz', sa.Float(), nullable=False),
    sa.Column('boost_clock_ghz', sa.Float(), nullable=False),
    sa.Column('tdp_w', sa.Integer(), nullable=False),
    sa.Column('memory_support', sa.String(length=60), nullable=False),
    sa.Column('memory_channels', sa.Integer(), nullable=False),
    sa.Column('single_thread_score', sa.Float(), nullable=False),
    sa.Column('multi_thread_score', sa.Float(), nullable=False),
    sa.Column('perf_class', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('source_title', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=False),
    sa.Column('source_date', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('draft', 'reviewed', 'published')", name='ck_status_values'),
    sa.CheckConstraint('multi_thread_score between 0.0 and 1.0', name='ck_cpu_multi'),
    sa.CheckConstraint('perf_class between 1 and 5', name='ck_cpu_class'),
    sa.CheckConstraint('single_thread_score between 0.0 and 1.0', name='ck_cpu_single'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', name='uq_hw_cpu_model')
    )
    with op.batch_alter_table('hardware_cpu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hardware_cpu_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_hardware_cpu_perf_class'), ['perf_class'], unique=False)

    op.create_table('hardware_gpu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('generation', sa.String(length=80), nullable=False),
    sa.Column('architecture', sa.String(length=80), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=False),
    sa.Column('vram_gb', sa.Float(), nullable=False),
    sa.Column('vram_type', sa.String(length=40), nullable=False),
    sa.Column('memory_bandwidth_gbs', sa.Float(), nullable=False),
    sa.Column('bus_width_bit', sa.Integer(), nullable=False),
    sa.Column('tdp_w', sa.Integer(), nullable=False),
    sa.Column('api_support', sa.JSON(), nullable=False),
    sa.Column('hw_features', sa.JSON(), nullable=False),
    sa.Column('raster_score', sa.Float(), nullable=False),
    sa.Column('rt_score', sa.Float(), nullable=False),
    sa.Column('perf_class', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('source_title', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=False),
    sa.Column('source_date', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('draft', 'reviewed', 'published')", name='ck_status_values'),
    sa.CheckConstraint('perf_class between 1 and 5', name='ck_gpu_class'),
    sa.CheckConstraint('raster_score between 0.0 and 1.0', name='ck_gpu_raster'),
    sa.CheckConstraint('rt_score between 0.0 and 1.0', name='ck_gpu_rt'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', name='uq_hw_gpu_model')
    )
    with op.batch_alter_table('hardware_gpu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hardware_gpu_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_hardware_gpu_perf_class'), ['perf_class'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('basket', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_public_id'), ['public_id'], unique=True)

    op.create_table('publication_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_code', sa.String(length=120), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=False),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publication_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_log_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_log_entity_code'), ['entity_code'], unique=False)

    op.create_table('validation_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_code', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subsystem', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tool_type', sa.String(length=40), nullable=False),
    sa.Column('docs_url', sa.String(length=600), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('draft', 'reviewed', 'published')", name='ck_status_values'),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_engine_tools_code')
    )
    with op.batch_alter_table('engine_tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_tools_code'), ['code'], unique=False)

    op.create_table('methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('pros', sa.JSON(), nullable=False),
    sa.Column('cons', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('recommended_stage', sa.String(length=20), nullable=False),
    sa.Column('late_cost', sa.String(length=20), nullable=False),
    sa.Column('calc_mode', sa.String(length=20), nullable=False),
    sa.Column('impact_cpu', sa.Integer(), nullable=False),
    sa.Column('impact_gpu', sa.Integer(), nullable=False),
    sa.Column('impact_ram', sa.Integer(), nullable=False),
    sa.Column('impact_vram', sa.Integer(), nullable=False),
    sa.Column('impact_disk', sa.Integer(), nullable=False),
    sa.Column('impact_network', sa.Integer(), nullable=False),
    sa.Column('quality_impact', sa.Integer(), nullable=False),
    sa.Column('concept_impact', sa.Integer(), nullable=False),
    sa.Column('performance_gain', sa.Float(), nullable=False),
    sa.Column('implementation_cost', sa.Integer(), nullable=False),
    sa.Column('complexity', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('requires_prototype', sa.Boolean(), nullable=False),
    sa.Column('applicable_formats', sa.JSON(), nullable=False),
    sa.Column('applicable_world_types', sa.JSON(), nullable=False),
    sa.Column('applicable_engines', sa.JSON(), nullable=False),
    sa.Column('applicable_platforms', sa.JSON(), nullable=False),
    sa.Column('requires_features', sa.JSON(), nullable=False),
    sa.Column('requires_hw_features', sa.JSON(), nullable=False),
    sa.Column('requires_conditions', sa.JSON(), nullable=False),
    sa.Column('min_scale', sa.String(length=20), nullable=True),
    sa.Column('verification_method', sa.Text(), nullable=False),
    sa.Column('verification_tools', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_title', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=False),
    sa.Column('source_date', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('draft', 'reviewed', 'published')", name='ck_status_values'),
    sa.CheckConstraint('complexity between 1 and 5', name='ck_methods_complexity'),
    sa.CheckConstraint('concept_impact between -2 and 0', name='ck_methods_concept'),
    sa.CheckConstraint('confidence between 0.0 and 1.0', name='ck_methods_confidence'),
    sa.CheckConstraint('impact_cpu between -3 and 3', name='ck_methods_impact_cpu'),
    sa.CheckConstraint('impact_disk between -3 and 3', name='ck_methods_impact_disk'),
    sa.CheckConstraint('impact_gpu between -3 and 3', name='ck_methods_impact_gpu'),
    sa.CheckConstraint('impact_network between -3 and 3', name='ck_methods_impact_network'),
    sa.CheckConstraint('impact_ram between -3 and 3', name='ck_methods_impact_ram'),
    sa.CheckConstraint('impact_vram between -3 and 3', name='ck_methods_impact_vram'),
    sa.CheckConstraint('implementation_cost between 1 and 5', name='ck_methods_cost'),
    sa.CheckConstraint('performance_gain between 0.0 and 1.0', name='ck_methods_gain'),
    sa.CheckConstraint('quality_impact between -2 and 2', name='ck_methods_quality'),
    sa.ForeignKeyConstraint(['function_id'], ['game_functions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_methods_code')
    )
    with op.batch_alter_table('methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_methods_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_methods_status'), ['status'], unique=False)

    op.create_table('method_engine_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=600), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('draft', 'reviewed', 'published')", name='ck_status_values'),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['engine_tools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method_id', 'tool_id', name='uq_method_tool')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('method_engine_links')
    with op.batch_alter_table('methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_methods_status'))
        batch_op.drop_index(batch_op.f('ix_methods_code'))

    op.drop_table('methods')
    with op.batch_alter_table('engine_tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_tools_code'))

    op.drop_table('engine_tools')
    op.drop_table('validation_issues')
    with op.batch_alter_table('publication_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_log_entity_code'))
        batch_op.drop_index(batch_op.f('ix_publication_log_entity'))

    op.drop_table('publication_log')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_public_id'))

    op.drop_table('projects')
    with op.batch_alter_table('hardware_gpu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hardware_gpu_perf_class'))
        batch_op.drop_index(batch_op.f('ix_hardware_gpu_model'))

    op.drop_table('hardware_gpu')
    with op.batch_alter_table('hardware_cpu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hardware_cpu_perf_class'))
        batch_op.drop_index(batch_op.f('ix_hardware_cpu_model'))

    op.drop_table('hardware_cpu')
    with op.batch_alter_table('game_functions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_functions_status'))
        batch_op.drop_index(batch_op.f('ix_game_functions_code'))

    op.drop_table('game_functions')
    with op.batch_alter_table('game_examples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_examples_status'))

    op.drop_table('game_examples')
    with op.batch_alter_table('engines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engines_code'))

    op.drop_table('engines')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicts_b_code'))
        batch_op.drop_index(batch_op.f('ix_conflicts_a_code'))

    op.drop_table('conflicts')
    # ### end Alembic commands ###
