"""drop_game_examples_and_projects

Revision ID: e103004d1fae
Revises: 9547c3d766db
Create Date: 2026-09-08 15:58:35.236147

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# Идентификатор ревизии; используется Alembic.
revision: str = 'e103004d1fae'
down_revision: str | None = '9547c3d766db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Удалить устаревшие таблицы game_examples и projects.

    Таблицы могут отсутствовать в базах, созданных после удаления
    соответствующих ORM-моделей из metadata, поэтому проверяем
    существование перед удалением.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())

    if "game_examples" in tables:
        op.drop_index("ix_game_examples_status", table_name="game_examples")
        op.drop_table("game_examples")
    if "projects" in tables:
        op.drop_index("ix_projects_public_id", table_name="projects")
        op.drop_table("projects")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('public_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('profile', sqlite.JSON(), nullable=False),
    sa.Column('basket', sqlite.JSON(), nullable=False),
    sa.Column('result', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_public_id'), ['public_id'], unique=1)

    op.create_table('game_examples',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('developer', sa.VARCHAR(length=200), nullable=False),
    sa.Column('engine', sa.VARCHAR(length=80), nullable=False),
    sa.Column('format', sa.VARCHAR(length=10), nullable=False),
    sa.Column('world_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('scale', sa.VARCHAR(length=20), nullable=False),
    sa.Column('platforms', sqlite.JSON(), nullable=False),
    sa.Column('target_resolution', sa.VARCHAR(length=20), nullable=False),
    sa.Column('target_fps', sa.INTEGER(), nullable=False),
    sa.Column('object_count_level', sa.VARCHAR(length=10), nullable=False),
    sa.Column('npc_count_level', sa.VARCHAR(length=10), nullable=False),
    sa.Column('multiplayer', sa.BOOLEAN(), nullable=False),
    sa.Column('player_count', sa.INTEGER(), nullable=False),
    sa.Column('features', sqlite.JSON(), nullable=False),
    sa.Column('optimizations_used', sqlite.JSON(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('performance_outcome', sa.TEXT(), nullable=False),
    sa.Column('source_title', sa.VARCHAR(length=300), nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=600), nullable=False),
    sa.Column('source_date', sa.VARCHAR(length=20), nullable=False),
    sa.Column('verified_by', sa.VARCHAR(length=30), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.CheckConstraint("status in ('draft', 'reviewed', 'published')", name=op.f('ck_status_values')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', name=op.f('uq_game_examples_title'))
    )
    with op.batch_alter_table('game_examples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_examples_status'), ['status'], unique=False)

    # ### end Alembic commands ###
