"""Каталог игровых функций и технических подсистем проекта."""
from __future__ import annotations

from .sources import src

# Форматы: 2D / 2.5D / 3D. Типы мира: linear / hub / arena / open_world / procedural / sandbox.
GAME_FUNCTIONS: list[dict] = [
    {
        "code": "open_world_streaming",
        "name": "Потоковая загрузка открытого мира",
        "description": "Непрерывная подгрузка и выгрузка частей мира при движении игрока без экранов загрузки.",
        "category": "Мир и загрузка",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "procedural", "sandbox"],
        "sort_order": 10,
        "source_key": "UE_WORLDPARTITION",
    },
    {
        "code": "large_scale_terrain",
        "name": "Крупномасштабный ландшафт",
        "description": "Рендер обширных поверхностей с сохранением детализации вблизи и обобщением вдали.",
        "category": "Мир и загрузка",
        "formats": ["3D", "2.5D"],
        "typical_world_types": ["open_world", "procedural", "sandbox", "hub"],
        "sort_order": 20,
        "source_key": "UE_NANITE",
    },
    {
        "code": "procedural_vegetation",
        "name": "Растительность и объекты окружения",
        "description": "Массовое размещение деревьев, травы, камней и прочих повторяющихся объектов.",
        "category": "Мир и загрузка",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "procedural", "sandbox", "linear"],
        "sort_order": 30,
        "source_key": "UE_ISM",
    },
    {
        "code": "dynamic_global_illumination",
        "name": "Динамическое глобальное освещение",
        "description": "Переотражённый свет, пересчитываемый при изменении освещения и геометрии в рантайме.",
        "category": "Освещение",
        "formats": ["3D", "2.5D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 40,
        "source_key": "UE_LUMEN",
    },
    {
        "code": "baked_lighting",
        "name": "Запечённое освещение",
        "description": "Предварительный расчёт освещения статической геометрии в лайтмапы и зонды.",
        "category": "Освещение",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["linear", "hub", "arena"],
        "sort_order": 50,
        "source_key": "WIKI_LIGHTMAP",
    },
    {
        "code": "dynamic_shadows",
        "name": "Динамические тени",
        "description": "Тени от подвижных источников света и подвижных объектов, пересчитываемые каждый кадр.",
        "category": "Освещение",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 60,
        "source_key": "WIKI_SHADOWMAP",
    },
    {
        "code": "particle_systems",
        "name": "Системы частиц",
        "description": "Визуальные эффекты из большого числа элементов: дым, огонь, искры, обломки.",
        "category": "Визуальные эффекты",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 70,
        "source_key": "WIKI_PARTICLES",
    },
    {
        "code": "physics_simulation",
        "name": "Физическая симуляция",
        "description": "Твёрдые тела, сочленения, разрушения и взаимодействие объектов с учётом коллизий.",
        "category": "Симуляция",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 80,
        "source_key": "UE_CHAOS",
    },
    {
        "code": "character_animation",
        "name": "Анимация персонажей",
        "description": "Скелетная анимация, скиннинг, смешивание и IK для персонажей и существ.",
        "category": "Персонажи",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 90,
        "source_key": "WIKI_SKINNING",
    },
    {
        "code": "crowd_simulation",
        "name": "Толпы NPC",
        "description": "Одновременная симуляция и отрисовка десятков и сотен NPC в кадре.",
        "category": "Персонажи",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "sandbox"],
        "sort_order": 100,
        "source_key": "UE_MASS",
    },
    {
        "code": "ai_pathfinding",
        "name": "ИИ и поиск пути",
        "description": "Навигация агентов по миру с обходом препятствий и динамикой окружения.",
        "category": "Симуляция",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 110,
        "source_key": "WIKI_NAVMESH",
    },
    {
        "code": "water_simulation",
        "name": "Водные поверхности",
        "description": "Поверхность воды с волнами, отражениями, преломлением и взаимодействием.",
        "category": "Визуальные эффекты",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "procedural", "sandbox", "linear"],
        "sort_order": 120,
        "source_key": "WIKI_GERSTNER",
    },
    {
        "code": "volumetric_effects",
        "name": "Объёмные эффекты (туман, облака, дымка)",
        "description": "Рассеивание света в объёме: туман, облака, световые лучи, атмосферная дымка.",
        "category": "Визуальные эффекты",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 130,
        "source_key": "WIKI_VOLUMETRIC",
    },
    {
        "code": "post_processing",
        "name": "Постобработка изображения",
        "description": "Экранные эффекты после основного рендера: сглаживание, масштабирование, цветокоррекция, свечение.",
        "category": "Рендер",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 140,
        "source_key": "WIKI_TAA",
    },
    {
        "code": "rendering_architecture",
        "name": "Архитектура рендера",
        "description": "Организация render graph, проходов, буферов, шейдеров, PSO и отсечения объектов.",
        "category": "Рендер",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 145,
        "source_key": "WIKI_DEFERRED",
    },
    {
        "code": "render_scalability",
        "name": "Масштабирование качества",
        "description": "Тиры качества, динамические ограничения и адаптация графики под разные классы оборудования.",
        "category": "Рендер",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 146,
        "source_key": "UE_SCALABILITY",
    },
    {
        "code": "geometry_pipeline",
        "name": "Конвейер геометрии",
        "description": "Подготовка мешей, индексов, вершин, геометрических кластеров и затрат на draw calls.",
        "category": "Рендер",
        "formats": ["3D", "2.5D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 147,
        "source_key": "MESHOPT",
    },
    {
        "code": "upscaling_frame_generation",
        "name": "Масштабирование и генерация кадров",
        "description": "Временное/ML-масштабирование изображения и синтез промежуточных кадров.",
        "category": "Рендер",
        "formats": ["3D", "2.5D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 148,
        "source_key": "WIKI_DLSS",
    },
    {
        "code": "storage_streaming",
        "name": "Потоковая работа с накопителем",
        "description": "Планирование чтения, кэширования, декомпрессии и бюджета streaming pool.",
        "category": "Мир и загрузка",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "procedural", "sandbox", "linear", "hub"],
        "sort_order": 31,
        "source_key": "UNITY_TEXTURE_STREAMING",
    },
    {
        "code": "audio_system",
        "name": "Аудиосистема",
        "description": "Потоковая загрузка, компрессия, пространственное позиционирование и окклюзия звука.",
        "category": "Звук",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 160,
        "source_key": "HUNT_AUDIO",
    },
    {
        "code": "build_delivery",
        "name": "Сборка и доставка контента",
        "description": "Размер сборки, время старта, патчи, чанки и доставка контента пользователю.",
        "category": "Производство",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 170,
        "source_key": "UNITY_ADDRESSABLES",
    },
    {
        "code": "runtime_memory",
        "name": "Память и сборка мусора",
        "description": "Аллокации, управляемая куча, кэши и бюджеты памяти в горячих циклах.",
        "category": "Производительность",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 180,
        "source_key": "UNITY_GC_BEST_PRACTICES",
    },
    {
        "code": "destruction_simulation",
        "name": "Разрушения и геометрические кэши",
        "description": "Интерактивные разрушения и запечённые кэши деформаций/вершин.",
        "category": "Симуляция",
        "formats": ["3D", "2.5D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "sandbox"],
        "sort_order": 185,
        "source_key": "DOOM_ETERNAL",
    },
    {
        "code": "project_architecture",
        "name": "Архитектура проекта",
        "description": "Композиция, разделение данных и механик, сервисы и каркас запуска проекта.",
        "category": "Производство",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 190,
        "source_key": "WIKI_DOD",
    },
    {
        "code": "art_pipeline",
        "name": "Арт-пайплайн",
        "description": "Ретопология, запекание нормалей, подготовка ассетов и выбор визуального стиля.",
        "category": "Производство контента",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 200,
        "source_key": "WIKI_LIGHTMAP",
    },
    {
        "code": "split_screen_rendering",
        "name": "Split-screen рендеринг",
        "description": "Бюджет нескольких камер и вьюпортов в локальном кооперативе.",
        "category": "Рендер",
        "formats": ["3D", "2.5D"],
        "typical_world_types": ["linear", "hub", "arena", "sandbox"],
        "sort_order": 210,
        "source_key": "DF_ITTakesTWO",
    },
    {
        "code": "multiplayer_netcode",
        "name": "Сетевой код мультиплеера",
        "description": "Синхронизация состояния между клиентами и сервером, компенсация задержек, репликация.",
        "category": "Сеть",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "arena", "hub", "sandbox", "procedural"],
        "sort_order": 150,
        "source_key": "WIKI_PREDICTION",
    },
    {
        "code": "save_system",
        "name": "Система сохранений",
        "description": "Сохранение и загрузка прогресса: слоты, автосейвы, версионирование формата, устойчивость к обрыву записи.",
        "category": "Прогресс и данные",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 155,
        "source_key": "UE_SAVEGAME",
    },
    # --- Трассировка лучей -------------------------------------------------
    # Отдельные функции, а не варианты «освещения вообще»: стоимость полной
    # трассировки пути и выборочных трассировочных эффектов различается на
    # порядок, поэтому в расчёте это разные статьи бюджета.
    {
        "code": "path_tracing",
        "name": "Трассировка пути",
        "description": "Полное решение уравнения переноса излучения трассировкой пути: весь свет кадра считается лучами, без разделения на растровые проходы.",
        "category": "Освещение",
        "formats": ["3D"],
        "typical_world_types": ["linear", "hub", "arena", "open_world"],
        "sort_order": 42,
        "source_key": "WIKI_PATH_TRACING",
    },
    {
        "code": "ray_traced_effects",
        "name": "Трассировочные эффекты (тени, отражения, AO)",
        "description": "Выборочная трассировка лучей поверх растрового кадра: отражения, тени, ambient occlusion, глобальное освещение.",
        "category": "Освещение",
        "formats": ["3D"],
        "typical_world_types": ["linear", "hub", "arena", "open_world"],
        "sort_order": 44,
        "source_key": "WIKI_RAY_TRACING",
    },
    {
        "code": "dynamic_lighting",
        "name": "Множественные динамические источники света",
        "description": "Десятки и сотни подвижных источников света в кадре, влияющих на материалы без предварительного расчёта.",
        "category": "Освещение",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "sandbox"],
        "sort_order": 46,
        "source_key": "WIKI_GLOBAL_ILLUMINATION",
    },
    {
        "code": "mesh_shaders",
        "name": "Меш-шейдеры и генерация геометрии на GPU",
        "description": "Программируемая сборка и отсечение примитивов на GPU: мешлеты, task/mesh-стадии, процедурная генерация без участия CPU.",
        "category": "Рендер",
        "formats": ["3D", "2.5D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "procedural", "sandbox"],
        "sort_order": 149,
        "source_key": "MS_MESH_SHADER",
    },
    {
        "code": "procedural_terrain",
        "name": "Процедурная генерация ландшафта и мира",
        "description": "Генерация рельефа, биомов и наполнения мира по правилам в рантайме или при сборке, вместо размечения вручную.",
        "category": "Мир и загрузка",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["procedural", "open_world", "sandbox"],
        "sort_order": 25,
        "source_key": "WIKI_PROCEDURAL",
    },
    # --- Геймплейные и симуляционные подсистемы ----------------------------
    # Введены по результатам аудита: признаки вида «нано-костюм», «геройские
    # способности», «транспорт», «стелс-ИИ» встречаются в партиях часто и
    # раньше не попадали ни в одну функцию каталога.
    {
        "code": "gameplay_ability_system",
        "name": "Геймплейные способности и модификаторы",
        "description": "Наборы способностей персонажа, модификаторы состояния, режимы брони и усиления, влияющие на симуляцию и отрисовку.",
        "category": "Геймплей",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "sandbox"],
        "sort_order": 95,
        "source_key": "GPP_STATE",
    },
    {
        "code": "vehicle_simulation",
        "name": "Транспорт и физика движения",
        "description": "Управляемые средства передвижения: колёсная и гусеничная динамика, полёт, плавание, повреждения и взаимодействие со средой.",
        "category": "Симуляция",
        "formats": ["3D", "2.5D"],
        "typical_world_types": ["open_world", "arena", "sandbox", "linear"],
        "sort_order": 85,
        "source_key": "WIKI_VEHICLE_DYNAMICS",
    },
    {
        "code": "advanced_npc_ai",
        "name": "Поведенческий ИИ NPC",
        "description": "Индивидуальное поведение неигровых персонажей: деревья поведений и конечные автоматы, стелс-реакции, компаньоны, режиссёр событий.",
        "category": "Симуляция",
        "formats": ["3D", "2.5D", "2D"],
        "typical_world_types": ["open_world", "linear", "hub", "arena", "sandbox"],
        "sort_order": 115,
        "source_key": "WIKI_GAME_AI",
    },
]


def with_sources() -> list[dict]:
    """Добавить поля источника, не изменяя исходный каталог функций."""
    out = []
    for fn in GAME_FUNCTIONS:
        data = dict(fn)
        s = src(data.pop("source_key", None))
        data["source_title"] = s["title"]
        data["source_url"] = s["url"]
        data["source_date"] = s["date"]
        out.append(data)
    return out
